### ISSUE TITLE
Can't click checkboxes for include

### ISSUE THREAD

**Issue by yiar** [IsakNyberg/kth-gpa-calculator#1]
Hi! Seems like a great tool, can't believe the schools don't have official ones!

Unfortunately I can't use it. I tried Chrome, Firefox and Safari and turned off adblockers, but still can't press the checkboxes to include my courses.

I didn't study at KTH but at GU/Chalmers. My grade system was U/G/VG, so maybe this is why it doesn't work?
Can't find how to calculate GPA based on this system so would love if you could include this in your tool (if this is the problem and not something else).

**Comment by IsakNyberg** [comment]
Unfortunately the website it only made for the A-E grade scale used at KTH, and not for other universities.
